[platform]
display_name = Gmail
name = gmail
; proto_id: 0 = OAuth2, 1 = PNBA
proto_id = 0
; cat_id: 0 = Email, 1 = Message, 2 = Text, 3 = Bridge
cat_id = 0
; true or false
supports_offline_first = false
icon_svg = https://raw.githubusercontent.com/smswithoutborders/gmail-oauth2-adapter/main/icons/gmail.svg
icon_png = https://raw.githubusercontent.com/smswithoutborders/gmail-oauth2-adapter/main/icons/gmail.png

[author]
name = Afkanerd Developers 
email = developers@smswithoutborders.com 
